### PR TITLE
Pull marinus' changes into master

### PR DESCRIPTION
**Pull request by marinuslouw**

### CODE REVIEW

**Comment by datawookie** [comment]
Are you sure that's all you needed to do? What about when you run the code again? Where will the HTML files be created?

**Comment by marinuslouw** [comment]
Yeah, no, my commit message is a bit incomplete. I changed the filepath to `docs/` as well.

**Comment by datawookie** [comment]
Hmmm. Just looked at the files and that does not appear to be included.

I'm sure that we had a conversation about this sort of thing earlier today... Please can we not do this?

**Comment by datawookie** [comment]
Aha.

**Comment by datawookie** [comment]
Cool. So for the moment you can access the published CVs like this:

<https://exegetic-analytics.github.io/exegetic-resume/docs/marinus-louw.html>

I'll set up an `exegetic.biz` sub-domain so that this URL is simpler.

**Pull request merged**
